name: Sketch e2e Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Sketch Tests
        uses: cypress-io/github-action@v2
        with:
          record: true
          browser: chrome
        env:
          # pass the Dashboard record key as an environment variable
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          CYPRESS_PASS: ${{ secrets.CYPRESS_PASS }}
          CYPRESS_EMAIL: ${{ secrets.CYPRESS_EMAIL }}